version: 2.1

jobs:
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8e:6d:d1:40:8f:c3:02:93:3a:a7:a1:2d:72:e9:b8:2c"
          
      - run:
          name: "Install ansible"
          command: |
            sudo python3 get-pip.py
            sudo python3 -m pip install ansible
      
      - run:
          name: "Run Playbook and Configure Server"
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  my_workflow:
    jobs:
      - configure-infrastructure