version: 2.1

jobs:
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8e:6d:d1:40:8f:c3:02:93:3a:a7:a1:2d:72:e9:b8:2c"
          
      - run:
          name: "Install ansible"
          command: |
            apk add --update ansible
      
      - run:
          name: "Run Playbook and Configure Server"
          command: |
            ansible-playbook -i inventory main-remote.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke-test
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL}
            then
            return 0
            else
            return 1
            fi

workflows:
  my_workflow:
    jobs:
      - smoke-test