---
- name: "update yum packages"
  become: true
  yum:
    update_cache: yes

#  - name: "Upgrade packages"
#    become: true
#    yum:
#      upgrade: yes

- name: "download nodejs repo"
  shell: |
    curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash - 

- name: "Install nodejs and npm"
  become: true
  yum:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Creates dir"
  file:
    path: ~/web
    state: directory

- name: "Copy index page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Executing node"
  shell: |
    pm2 start ~/web/index.js -f

